language: python

python:
  - 3.6

install:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install numpydoc
  - pip install jupyter jupyter_client nbconvert nbval

script:
  # Use Sphinx to make the html docs
  - cd docs
  - make html
  - touch _build/html/.nojekyll
  # roughtly execute every jupyter notebook we fine
  - find . -name requirements.txt|xargs cat|xargs pip install -U 
  - find . -name "*.ipynb" |xargs jupyter nbconvert --to notebook --execute 
# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs/_build/html/
  target-branch: gh-pages # This is the default branch but I add it here anyway
  on:
    branch: master
